name: Terraform Deploy

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform Init Plan Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

     

      # Terraform Apply
      - name: Terraform Apply
        run: destroy -auto-approve
